import type { Metadata } from 'next'
import Link from 'next/link'
import { CheckCircle2, MessageCircle, ShieldCheck } from 'lucide-react'
import { PageHero } from '@/components/page-hero'

export const metadata: Metadata = { title: 'About', description: 'Learn about Secure Monitoring’s human-led managed security operations approach.' }
const principles = ['Human-led monitoring and operational judgement', 'Clear communication with designated employees', 'Agreed incident escalation procedures', 'Practical WhatsApp coordination', 'Incident documentation and reporting']

export default function AboutPage() {
 return <><PageHero eyebrow="About Secure Monitoring" title="Security support designed around operational response.">Secure Monitoring helps teams use their existing camera infrastructure as part of a practical, human-led security operation.</PageHero><section className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8"><div><h2 className="text-3xl font-bold">What we focus on</h2><p className="mt-5 leading-7 text-muted-foreground">We focus on the operational layer behind monitoring: seeing an actionable incident, beginning the response path, communicating with the right people, and recording what happened. Our approach is built around agreed procedures rather than generic software claims.</p><p className="mt-5 leading-7 text-muted-foreground">For shoplifting incidents, monitoring can support designated employee contact by phone. On the Professional plan, law-enforcement contact may be made when appropriate, authorized, and included in the agreed procedure.</p><Link href="/operations" className="mt-6 inline-flex rounded-md bg-primary px-5 py-3 font-semibold text-primary-foreground hover:bg-accent">How operations work</Link></div><aside className="rounded-xl border border-border bg-card p-7"><ShieldCheck className="h-9 w-9 text-primary" /><h2 className="mt-5 text-2xl font-bold">Our operating principles</h2><ul className="mt-6 space-y-4">{principles.map(item=><li key={item} className="flex gap-3 text-sm leading-6"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-primary" />{item}</li>)}</ul><div className="mt-8 border-t border-border pt-6"><p className="text-sm text-muted-foreground">A response target is not a guarantee of resolution or law-enforcement response. It is a target for our monitoring team to initiate its operational response when an actionable incident is detected.</p></div></aside></section><section className="border-y border-border bg-card"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><MessageCircle className="h-8 w-8 text-primary" /><h2 className="mt-4 text-2xl font-bold">Start with a consultation.</h2><p className="mt-3 max-w-2xl text-muted-foreground">We can discuss your monitoring priorities, existing setup, team contacts, and response expectations.</p><Link href="/contact" className="mt-5 inline-block text-sm font-semibold text-primary hover:underline">Contact Secure Monitoring →</Link></div></section></>
}