import type { Metadata } from 'next'
import Link from 'next/link'
import { Check } from 'lucide-react'
import { PageHero } from '@/components/page-hero'

export const metadata: Metadata = { title: 'Pricing', description: 'Managed security operations plans for human-led monitoring, incident response, escalation, and reporting.' }
const plans = [
 { name: 'Basic', price: '$199', note: 'per month', intro: 'Essential monitoring and employee escalation.', features: ['Employee monitoring', 'Shoplifting monitoring', 'Night camera monitoring', '30-second response target', 'Employee notification by phone for detected shoplifting incidents', 'WhatsApp alerts and coordination', 'Incident reporting', 'Operational support through WhatsApp'] },
 { name: 'Professional', price: '$299', note: 'per month', intro: 'Enhanced escalation and response coordination.', featured: true, features: ['Everything in Basic', 'Enhanced shoplifting incident escalation', '30-second response target', 'Direct contact with designated employees', 'Law-enforcement contact when appropriate and authorized', 'Priority incident escalation', 'Enhanced incident reporting', 'More comprehensive response coordination'] },
 { name: 'Enterprise', price: 'From $699', note: 'per month', intro: 'Customizable operations for complex requirements.', features: ['Everything in Professional', 'Multi-location operations', 'Customized monitoring requirements', 'Customized escalation procedures', 'Dedicated operational support', 'Tailored reporting', 'Pricing adapted to locations, cameras, coverage, and operational complexity'] },
]

export default function PricingPage() {
 return <><PageHero eyebrow="Pricing" title="Choose the operational support that fits your requirements.">Plans are recurring managed services. Enterprise requirements are scoped and priced around the operational needs of your locations, cameras, coverage, and response procedures.</PageHero><section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-3">{plans.map(plan=><article key={plan.name} className={`relative flex flex-col rounded-xl border p-6 ${plan.featured ? 'border-primary bg-card shadow-xl ring-1 ring-primary' : 'border-border bg-card'}`}>{plan.featured && <span className="absolute -top-3 left-6 rounded-full bg-primary px-3 py-1 text-xs font-bold text-primary-foreground">RECOMMENDED</span>}<h2 className="text-2xl font-bold">{plan.name}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{plan.intro}</p><div className="my-6"><span className="text-4xl font-bold">{plan.price}</span><span className="ml-1 text-sm text-muted-foreground">/{plan.note}</span></div><ul className="space-y-3 text-sm">{plan.features.map(feature=><li key={feature} className="flex gap-2"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{feature}</li>)}</ul><Link href="/contact" className={`mt-8 block rounded-md px-4 py-3 text-center text-sm font-semibold ${plan.featured ? 'bg-primary text-primary-foreground hover:bg-accent' : 'border border-border hover:bg-secondary'}`}>{plan.name === 'Enterprise' ? 'Discuss enterprise requirements' : 'Book a consultation'}</Link></article>)}</div><p className="mx-auto mt-10 max-w-3xl text-center text-sm leading-6 text-muted-foreground">The 30-second figure is a monitoring/response initiation target when an actionable incident is detected. Law-enforcement contact is available only where appropriate, authorized, and covered by the agreed plan; it does not guarantee a police response.</p></section></>
}